<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Aiden Sutherland’s Data Analysis Portfolio - cdcdata-exercise</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Aiden Sutherland’s Data Analysis Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/products/report/starter-analysis-report.html">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../coding-exercise/coding-exercise.html">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentation-exercise/presentation-exercise.html">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tidytuesday-exercise/tidytuesday-exercise.html">
 <span class="dropdown-text">Tidy Tuesday Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-exercise/data-exercise.html">
 <span class="dropdown-text">Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cdcdata-exercise/cdcdata-exercise.html">
 <span class="dropdown-text">CDC Data Exercise</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/AIdenSutherland13/AidenSutherland-P2-portfolio"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">cdcdata-exercise</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The data set Provisional_COVID-19_Deaths_by_Sex_and_Age_20240703.csv shows data of deaths involving COVID-19, pneumonia, and influenza reported to NCHS by sex, age group, and jurisdiction of occurrence.It was last updated on September 27th, 2023.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'gridExtra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
</div>
<p>Here is a quick preview of what the data set looks like after importing it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Path when Aiden is loading data</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># covid_data &lt;- read.csv("~/GitHub/AidenSutherland-P2-portfolio/AidenSutherland-P2-portfolio/cdcdata-exercise/Provisional_COVID-19_Deaths_by_Sex_and_Age_20240703.csv")</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Path when Zane is loading data</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>covid_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Provisional_COVID-19_Deaths_by_Sex_and_Age_20240703.csv"</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(covid_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Data.As.Of Start.Date   End.Date    Group Year Month         State       Sex
1 09/27/2023 01/01/2020 09/23/2023 By Total   NA    NA United States All Sexes
2 09/27/2023 01/01/2020 09/23/2023 By Total   NA    NA United States All Sexes
3 09/27/2023 01/01/2020 09/23/2023 By Total   NA    NA United States All Sexes
4 09/27/2023 01/01/2020 09/23/2023 By Total   NA    NA United States All Sexes
5 09/27/2023 01/01/2020 09/23/2023 By Total   NA    NA United States All Sexes
6 09/27/2023 01/01/2020 09/23/2023 By Total   NA    NA United States All Sexes
     Age.Group COVID.19.Deaths Total.Deaths Pneumonia.Deaths
1     All Ages         1146774     12303399          1162844
2 Under 1 year             519        73213             1056
3   0-17 years            1696       130970             2961
4    1-4 years             285        14299              692
5   5-14 years             509        22008              818
6  15-24 years            3021       133459             3175
  Pneumonia.and.COVID.19.Deaths Influenza.Deaths
1                        569264            22229
2                            95               64
3                           424              509
4                            66              177
5                           143              219
6                          1257              206
  Pneumonia..Influenza..or.COVID.19.Deaths Footnote
1                                  1760095         
2                                     1541         
3                                     4716         
4                                     1079         
5                                     1390         
6                                     5133         </code></pre>
</div>
</div>
<p>Here i changed the columns to be separated with _ instead of . as well as removing any rows containing “NA” as well as removing the footnote column and any row containing the United States instead of the actual state in the “state” column.</p>
<p>The Age_Group column was a mess, so I filtered out the data that seemed to have different age group increments so we only have one age group to go with.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(covid_data) <span class="ot">&lt;-</span> <span class="fu">str_replace_all</span>(<span class="fu">colnames</span>(covid_data), <span class="st">"[^[:alnum:]_]"</span>, <span class="st">"_"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>covid_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(covid_data)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>covid_data <span class="ot">&lt;-</span> covid_data <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Footnote)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>covid_data <span class="ot">&lt;-</span> covid_data <span class="sc">%&gt;%</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(State <span class="sc">!=</span> <span class="st">"United States"</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>covid_data <span class="ot">&lt;-</span> covid_data <span class="sc">%&gt;%</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Age_Group <span class="sc">!=</span> <span class="st">"0-17 years"</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>covid_data <span class="ot">&lt;-</span> covid_data <span class="sc">%&gt;%</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Age_Group <span class="sc">!=</span> <span class="st">"18-29 years"</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>covid_data <span class="ot">&lt;-</span> covid_data <span class="sc">%&gt;%</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Age_Group <span class="sc">!=</span> <span class="st">"30-39 years"</span>)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>covid_data <span class="ot">&lt;-</span> covid_data <span class="sc">%&gt;%</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Age_Group <span class="sc">!=</span> <span class="st">"40-49 years"</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>covid_data <span class="ot">&lt;-</span> covid_data <span class="sc">%&gt;%</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Age_Group <span class="sc">!=</span> <span class="st">"50-59 years"</span>)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>covid_data <span class="ot">&lt;-</span> covid_data <span class="sc">%&gt;%</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Age_Group <span class="sc">!=</span> <span class="st">"50-64 years"</span>)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>covid_data <span class="ot">&lt;-</span> covid_data <span class="sc">%&gt;%</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Age_Group <span class="sc">!=</span> <span class="st">"All Ages"</span>)</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(covid_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Data_As_Of         Start_Date          End_Date            Group          
 Length:21496       Length:21496       Length:21496       Length:21496      
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
      Year          Month           State               Sex           
 Min.   :2020   Min.   : 1.000   Length:21496       Length:21496      
 1st Qu.:2020   1st Qu.: 4.000   Class :character   Class :character  
 Median :2021   Median : 7.000   Mode  :character   Mode  :character  
 Mean   :2021   Mean   : 6.537                                        
 3rd Qu.:2022   3rd Qu.: 9.000                                        
 Max.   :2023   Max.   :12.000                                        
  Age_Group         COVID_19_Deaths    Total_Deaths    Pneumonia_Deaths 
 Length:21496       Min.   :   0.00   Min.   :   0.0   Min.   :   0.00  
 Class :character   1st Qu.:   0.00   1st Qu.:  15.0   1st Qu.:   0.00  
 Mode  :character   Median :  16.00   Median : 131.0   Median :  16.00  
                    Mean   :  51.12   Mean   : 460.3   Mean   :  47.75  
                    3rd Qu.:  57.00   3rd Qu.: 634.2   3rd Qu.:  63.00  
                    Max.   :3949.00   Max.   :9932.0   Max.   :1824.00  
 Pneumonia_and_COVID_19_Deaths Influenza_Deaths  
 Min.   :   0.00               Min.   :  0.0000  
 1st Qu.:   0.00               1st Qu.:  0.0000  
 Median :  10.00               Median :  0.0000  
 Mean   :  25.61               Mean   :  0.7475  
 3rd Qu.:  27.00               3rd Qu.:  0.0000  
 Max.   :1576.00               Max.   :177.0000  
 Pneumonia__Influenza__or_COVID_19_Deaths
 Min.   :   0.0                          
 1st Qu.:   0.0                          
 Median :  25.0                          
 Mean   :  73.9                          
 3rd Qu.:  94.0                          
 Max.   :4198.0                          </code></pre>
</div>
</div>
<p>Here are the columns I selected for the final data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>selected_columns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Year"</span>, <span class="st">"Month"</span>, <span class="st">"State"</span>, <span class="st">"Sex"</span>, <span class="st">"Age_Group"</span>, <span class="st">"COVID_19_Deaths"</span>, <span class="st">"Total_Deaths"</span>, <span class="st">"Pneumonia_Deaths"</span>, <span class="st">"Pneumonia_and_COVID_19_Deaths"</span>, <span class="st">"Influenza_Deaths"</span>, <span class="st">"Pneumonia__Influenza__or_COVID_19_Deaths"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>covid_data_subset <span class="ot">&lt;-</span> covid_data <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(selected_columns))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>##EDA</p>
<p>Here is a summary of all the categorical variables I realize that NYC is in New York, however the population density of that city should be noted separately from other reports from the rest of the state.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>cat_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Year"</span>, <span class="st">"Month"</span>, <span class="st">"State"</span>, <span class="st">"Sex"</span>, <span class="st">"Age_Group"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (cat_var <span class="cf">in</span> cat_vars) {</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  cat_var_summary <span class="ot">&lt;-</span> covid_data_subset <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(<span class="sc">!!</span><span class="fu">sym</span>(cat_var)) <span class="sc">%&gt;%</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">percentage =</span> <span class="fu">round</span>(count <span class="sc">/</span> <span class="fu">sum</span>(count) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>))</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(cat_var_summary)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
   Year count percentage
  &lt;int&gt; &lt;int&gt;      &lt;dbl&gt;
1  2020  6308       29.3
2  2021  7713       35.9
3  2022  4408       20.5
4  2023  3067       14.3
# A tibble: 12 × 3
   Month count percentage
   &lt;int&gt; &lt;int&gt;      &lt;dbl&gt;
 1     1  1920       8.93
 2     2  1778       8.27
 3     3  1605       7.47
 4     4  1566       7.29
 5     5  1667       7.75
 6     6  1713       7.97
 7     7  1866       8.68
 8     8  2130       9.91
 9     9  2202      10.2 
10    10  1763       8.2 
11    11  1634       7.6 
12    12  1652       7.69
# A tibble: 53 × 3
   State                count percentage
   &lt;chr&gt;                &lt;int&gt;      &lt;dbl&gt;
 1 Alabama                394       1.83
 2 Alaska                 360       1.67
 3 Arizona                499       2.32
 4 Arkansas               384       1.79
 5 California             551       2.56
 6 Colorado               407       1.89
 7 Connecticut            415       1.93
 8 Delaware               356       1.66
 9 District of Columbia   286       1.33
10 Florida                434       2.02
# ℹ 43 more rows
# A tibble: 3 × 3
  Sex       count percentage
  &lt;chr&gt;     &lt;int&gt;      &lt;dbl&gt;
1 All Sexes  7477       34.8
2 Female     6664       31  
3 Male       7355       34.2
# A tibble: 11 × 3
   Age_Group         count percentage
   &lt;chr&gt;             &lt;int&gt;      &lt;dbl&gt;
 1 1-4 years          1742       8.1 
 2 15-24 years        1939       9.02
 3 25-34 years        1346       6.26
 4 35-44 years        1260       5.86
 5 45-54 years        1657       7.71
 6 5-14 years         1482       6.89
 7 55-64 years        2016       9.38
 8 65-74 years        2347      10.9 
 9 75-84 years        2457      11.4 
10 85 years and over  2485      11.6 
11 Under 1 year       2765      12.9 </code></pre>
</div>
</div>
<p>Here is a summary of all of the continuous variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>cont_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"COVID_19_Deaths"</span>, <span class="st">"Total_Deaths"</span>, <span class="st">"Pneumonia_Deaths"</span>, <span class="st">"Pneumonia_and_COVID_19_Deaths"</span>, <span class="st">"Influenza_Deaths"</span>, <span class="st">"Pneumonia__Influenza__or_COVID_19_Deaths"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (cont_var <span class="cf">in</span> cont_vars) {</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  cont_var_summary <span class="ot">&lt;-</span> covid_data_subset <span class="sc">%&gt;%</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(<span class="sc">!!</span><span class="fu">sym</span>(cont_var), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">sd =</span> <span class="fu">sd</span>(<span class="sc">!!</span><span class="fu">sym</span>(cont_var), <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(cont_var_summary)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      mean       sd
1 51.11816 120.4679
      mean       sd
1 460.3108 761.6771
      mean       sd
1 47.75158 89.33372
      mean       sd
1 25.60993 60.04298
       mean       sd
1 0.7474879 5.008657
      mean       sd
1 73.90217 147.5101</code></pre>
</div>
</div>
<p>Here are corresponding plots for each continuous variable to check for normality.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (cont_var <span class="cf">in</span> cont_vars) {</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a> hist_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(covid_data_subset, <span class="fu">aes_string</span>(<span class="at">x =</span> cont_var)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..), <span class="at">binwidth =</span> <span class="dv">100</span>, <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span> <span class="fu">mean</span>(covid_data_subset[[cont_var]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">sd =</span> <span class="fu">sd</span>(covid_data_subset[[cont_var]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)), </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Histogram and Normal Curve of"</span>, cont_var),</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> cont_var,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Density"</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a> <span class="fu">print</span>(hist_plot)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-7-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-7-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-7-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here is A Q-Q plot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (cont_var <span class="cf">in</span> cont_vars) {</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  qq_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(covid_data_subset, <span class="fu">aes_string</span>(<span class="at">sample =</span> cont_var)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Q-Q Plot of"</span>, cont_var),</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Theoretical Quantiles"</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Sample Quantiles"</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Arrange the plots side by side</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">grid.arrange</span>(hist_plot, qq_plot, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-8-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-8-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-8-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-8-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="part-2---this-section-contributed-by-zane-chumley." class="level2">
<h2 class="anchored" data-anchor-id="part-2---this-section-contributed-by-zane-chumley.">Part 2 - This section contributed by ZANE CHUMLEY.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tracking processing time</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>ZC.Part2.start <span class="ot">&lt;-</span> <span class="fu">proc.time</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function for reporting processing time</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Times are accurate to 10ms on Windows</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># digits=2 will display to 1/100 seconds</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>ZC.ReportTime <span class="ot">&lt;-</span> <span class="cf">function</span>(ZC.section, ZC.timestamp)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  ZC.LineIntro <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"The "</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>                        , ZC.section</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>                        , <span class="st">" section took "</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>                        , <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  ZC.LineCPU <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="fu">round</span>(ZC.timestamp[<span class="dv">2</span>]</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>                            , <span class="at">digits=</span><span class="dv">2</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">" seconds of CPU time."</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>                      , <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  ZC.LineUser <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="fu">round</span>(ZC.timestamp[<span class="dv">1</span>]</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>                             , <span class="at">digit=</span><span class="dv">2</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>                       , <span class="st">" seconds of user time."</span></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>                       , <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>  ZC.LineTotal <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="fu">round</span>(ZC.timestamp[<span class="dv">3</span>]</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>                              , <span class="at">digits=</span><span class="dv">2</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>                       , <span class="st">" seconds of total time."</span></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>                       , <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>  ZC.printline <span class="ot">&lt;-</span> <span class="fu">paste</span>(ZC.LineIntro</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>                        , ZC.LineCPU</span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>                        , <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(ZC.printline)</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>  ZC.printline <span class="ot">&lt;-</span> <span class="fu">paste</span>(ZC.LineIntro</span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>                        , ZC.LineUser</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>                        , <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(ZC.printline)</span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>  ZC.printline <span class="ot">&lt;-</span> <span class="fu">paste</span>(ZC.LineIntro</span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a>                        , ZC.LineTotal</span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>                        , <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(ZC.printline)</span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function for reporting basic data frame characteristics</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>ZC.ReportDF <span class="ot">&lt;-</span> <span class="cf">function</span>(ZC.ThisName, ZC.ThisDataFrame)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  ZC.TheseDims <span class="ot">&lt;-</span> <span class="fu">dim</span>(ZC.ThisDataFrame)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  ZC.TheseRows <span class="ot">&lt;-</span> ZC.TheseDims[<span class="dv">1</span>]</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  ZC.TheseColumns <span class="ot">&lt;-</span> ZC.TheseDims[<span class="dv">2</span>]</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  ZC.ThisSize <span class="ot">&lt;-</span> <span class="fu">object.size</span>(ZC.ThisDataFrame)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Express size in Mb, not bytes</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  ZC.ThisSize <span class="ot">&lt;-</span> ZC.ThisSize<span class="sc">/</span>(<span class="dv">1024</span><span class="sc">*</span><span class="dv">1024</span>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  ZC.printline <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"The"</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>                        , ZC.ThisName</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>                        , <span class="st">"dataframe is"</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>                        , ZC.TheseRows</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>                        , <span class="st">"rows by"</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>                        , ZC.TheseColumns</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>                        , <span class="st">"columns, and takes"</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>                        , <span class="fu">round</span>(ZC.ThisSize, <span class="at">digits=</span><span class="dv">2</span>)</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>                        , <span class="st">"Mb of space."</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>                        , <span class="at">sep=</span><span class="st">" "</span>)</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(ZC.printline)</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="work-product-introduction" class="level3">
<h3 class="anchored" data-anchor-id="work-product-introduction">Work Product Introduction</h3>
<p>Collaborator will be synthesizing data analogous to the following original columns, with column for synthesized data in parentheses:</p>
<ul>
<li>Year (Year)</li>
<li>Month (Month)</li>
<li>State (State)</li>
<li>Sex (Gender)</li>
<li>Age_Group (AgeGroup)</li>
<li>COVID_19_Deaths (C19deaths)</li>
<li>Pneumonia_Deaths (PneuDeaths)</li>
<li>Pneumonia_and_COVID_19_Deaths (C19andPneuDeaths)</li>
<li>Influenza_Deaths (FluDeaths)</li>
<li>Pneumonia__Influenza__or_COVID_19_Deaths (C19orFluOrPneuDeaths)</li>
<li>Total_Deaths (AllDeaths)</li>
</ul>
<p>It appears the data summarizes fatalities by Year, Month, State, Sex, and Age Group:</p>
<ul>
<li>45 unique combinations of Year+Month: January 2020 through September 2023 inclusive</li>
<li>53 unique “states”, including:
<ul>
<li>District of Columbia</li>
<li>New York City (tracked separately from the rest of New York State)</li>
<li>Puerto Rico</li>
</ul></li>
<li>2 unique Genders</li>
<li>11 mutually-exclusive Age Groups:
<ul>
<li>under 1 year</li>
<li>1-4 years</li>
<li>5-14 years</li>
<li>15-24 years</li>
<li>25-34 years</li>
<li>35-44 years</li>
<li>45-54 years</li>
<li>55-64 years</li>
<li>65-74 years</li>
<li>75-84 years</li>
<li>85 years or older</li>
</ul></li>
</ul>
<p>This gives us a synthesized dataset of 45 * 53 * 2 * 11 = 52,470 rows.</p>
<p>Age is also alternatively grouped with the following values … the number of fatalities will be combinations, in whole or in part, of the fatalities recorded in the mutually-exclusive Age Groups:</p>
<ul>
<li>0-17 years</li>
<li>18-29 years</li>
<li>30-39 years</li>
<li>40-49 years</li>
<li>50-64 years</li>
</ul>
<p>This gives us an ancillary dataset of 45 * 52 * 2 * 5 = 23,400 rows. However, in Part 1 these rows were discarded, so they will not be synthesized.</p>
<p>There are also multiple summary rows also included in the data:</p>
<ul>
<li>An “All Ages” row for each combination of Year+Month+State+Gender, including summaries of same</li>
<li>An “All Sexes” row for each combination of Year+Month+State+(distinct)Age Group, including summaries of same</li>
<li>A “United States” row for each combination of Year+Month+Gender+(distinct)Age Group, including summaries of same</li>
<li>a “By Year” row (represented by an NA month) for each combination of Month+State+Gender+(distinct)Age Group, including summaries of same</li>
<li>an “All Year” row (represented by an NA year and NA month) for each combination of State+Gender+(distinct)Age Group, including summaries of same</li>
</ul>
<p>In Part 1, these rows were discarded as well, so they will not need to be synthesized.</p>
<p>Other observations regarding the data to be simulated:</p>
<ul>
<li>Pneumonia_and_COVID_19_Deaths is not a simple addition of Pneumonia and COVID_19 deaths; rather, it appears to be a sum of fatalities attributed to both Pneumonia and COVID_19. Therefore, it is always smaller than either fatality count: it is the intersection of these two causes of death.
<ul>
<li>This figure could be estimated as a function of the sum of Pneumonia and COVID_19 fatalities.</li>
</ul></li>
<li>Pneumonia__Influenza__or_COVID_19_Deaths is not a simple addition of these fatalities; rather, it appears to be fatalities caused by one of these diseases, but not included in the counts for other diseases.
<ul>
<li>This figure could be estimated as a function of the sum of Pneumonia, COVID_19, and Influenza fatalities.</li>
</ul></li>
<li>Total_Deaths is fatalities from all causes, not just the diseases examined bere. Therefore, it is always larger than the sum of the other causes.
<ul>
<li>This figure could be estimated as a a function of the sum of all other causes.</li>
</ul></li>
</ul>
</section>
<section id="work-product-summary" class="level3">
<h3 class="anchored" data-anchor-id="work-product-summary">Work Product Summary</h3>
<p>For each combination of Year+Month+State+Gender+Age_Group, the following six (6) columns will contain synthesized data:</p>
<ul>
<li>C19deaths
<ul>
<li>estimated as a function where AllDeaths is a parameter</li>
</ul></li>
<li>PneuDeaths
<ul>
<li>estimated as a function where AllDeaths is a parameter</li>
</ul></li>
<li>FluDeaths
<ul>
<li>estimated as a function where AllDeaths is a parameter</li>
</ul></li>
<li>C19andPneuDeaths
<ul>
<li>estimated as a function where (C19deaths+PneuDeaths) is a parameter</li>
</ul></li>
<li>C19orFluOrPneuDeaths
<ul>
<li>estimated as a function where (C19deaths+PneuDeaths+FluDeaths) is a parameter</li>
</ul></li>
<li>AllDeaths
<ul>
<li>estimated as a function where (C19deaths+PneuDeaths+FluDeaths) is a parameter</li>
</ul></li>
</ul>
<p>In the preparation section, the intercept (constant) and the coefficient(s) will be determined for a linear regression model applied to synthesize each column of data.</p>
<p>In the generation section, the base dataset will be synthesized. The alternate dataset and summary rows will not be tabulated, as these were discarded in Part 1.</p>
<p>In consideration of the resources required for these calculations, the processing time for each following section, as well as the overall processing time for this Part 2, will be calculated and reported.</p>
</section>
<section id="work-product-preparation" class="level3">
<h3 class="anchored" data-anchor-id="work-product-preparation">Work Product Preparation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tracking processing time</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>ZC.prep.start <span class="ot">&lt;-</span> <span class="fu">proc.time</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Developing the functions which will synthesize the data will involve:</p>
<ol type="1">
<li>loading a pristine copy of the data</li>
<li>removing extraneous columns</li>
<li>removing the summary rows and the alternate dataset</li>
<li>running linear regression on the surviving data</li>
</ol>
<p>Step 1: loading a pristine copy of the data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>ZC.data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Provisional_COVID-19_Deaths_by_Sex_and_Age_20240703.csv"</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>ZC.data <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(ZC.data)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ZC.ReportDF</span>(<span class="st">"original"</span>, ZC.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The original dataframe is 137700 rows by 16 columns, and takes 12.62 Mb of space."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(ZC.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Data.As.Of"                              
 [2] "Start.Date"                              
 [3] "End.Date"                                
 [4] "Group"                                   
 [5] "Year"                                    
 [6] "Month"                                   
 [7] "State"                                   
 [8] "Sex"                                     
 [9] "Age.Group"                               
[10] "COVID.19.Deaths"                         
[11] "Total.Deaths"                            
[12] "Pneumonia.Deaths"                        
[13] "Pneumonia.and.COVID.19.Deaths"           
[14] "Influenza.Deaths"                        
[15] "Pneumonia..Influenza..or.COVID.19.Deaths"
[16] "Footnote"                                </code></pre>
</div>
</div>
<p>Step 2: removing extraneous columns</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rather than an explicit removal, the dataset will be redefined as a subset of the columns of the pristine dataset</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The columns will also be re-ordered as they will be ordered when synthesized</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>ZC.data <span class="ot">&lt;-</span> ZC.data[<span class="fu">c</span>(<span class="st">"Year"</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"Month"</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"State"</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"Sex"</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"Age.Group"</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"COVID.19.Deaths"</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"Pneumonia.Deaths"</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"Influenza.Deaths"</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"Pneumonia.and.COVID.19.Deaths"</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"Pneumonia..Influenza..or.COVID.19.Deaths"</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"Total.Deaths"</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>                      )</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ZC.ReportDF</span>(<span class="st">"preserved column"</span>, ZC.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The preserved column dataframe is 137700 rows by 11 columns, and takes 7.36 Mb of space."</code></pre>
</div>
</div>
<p>Step 3: removing the summary rows and the alternate dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove all rows with an NA month</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Should remove all rows with an NA year as well</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>ZC.data <span class="ot">&lt;-</span> <span class="fu">subset</span>(ZC.data, <span class="sc">!</span>(<span class="fu">is.na</span>(Month)))</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove all rows with a state of "United States"</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>ZC.data <span class="ot">&lt;-</span> <span class="fu">subset</span>(ZC.data, <span class="sc">!</span>State<span class="sc">==</span><span class="st">"United States"</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove all rows with a gender of "All Sexes"</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>ZC.data <span class="ot">&lt;-</span> <span class="fu">subset</span>(ZC.data, <span class="sc">!</span>Sex<span class="sc">==</span><span class="st">"All Sexes"</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove all rows with an age group of "All Ages"</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>ZC.data <span class="ot">&lt;-</span> <span class="fu">subset</span>(ZC.data, <span class="sc">!</span>Age.Group<span class="sc">==</span><span class="st">"All Ages"</span>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Removing the alternate dataset</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>ZC.data <span class="ot">&lt;-</span> <span class="fu">subset</span>(ZC.data, <span class="sc">!</span>Age.Group<span class="sc">==</span><span class="st">"0-17 years"</span>)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>ZC.data <span class="ot">&lt;-</span> <span class="fu">subset</span>(ZC.data, <span class="sc">!</span>Age.Group<span class="sc">==</span><span class="st">"18-29 years"</span>)</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>ZC.data <span class="ot">&lt;-</span> <span class="fu">subset</span>(ZC.data, <span class="sc">!</span>Age.Group<span class="sc">==</span><span class="st">"30-39 years"</span>)</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>ZC.data <span class="ot">&lt;-</span> <span class="fu">subset</span>(ZC.data, <span class="sc">!</span>Age.Group<span class="sc">==</span><span class="st">"40-49 years"</span>)</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>ZC.data <span class="ot">&lt;-</span> <span class="fu">subset</span>(ZC.data, <span class="sc">!</span>Age.Group<span class="sc">==</span><span class="st">"50-64 years"</span>)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ZC.ReportDF</span>(<span class="st">"no summary, no alternate"</span>, ZC.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The no summary, no alternate dataframe is 52470 rows by 11 columns, and takes 3.01 Mb of space."</code></pre>
</div>
</div>
<p>Earlier, a base dataset of 52,470 rows was estimated. The model dataset now has the identical number rows. Ideally, the model dataset would have the same number of rows as the synthesized base dataset, so we are good to go.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The final dataset in Part 1 was 21,496 rows, whereas the final dataset in Part 2 will be 52,470 rows. The collaborator was unable to fully account for the difference, but a partial explanation was found in the exclusion of NA data in Part 1, whereas in Part 2, the inclusions of NA will be addressed during synthesis.</p>
</div>
</div>
<p>Step 4: running linear regression on the surviving data</p>
<p>After each model is created, the intercept and coefficient(s) will be stored for future use. Then, a summary of the model will be displayed</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear Regression for C19deaths</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>ZC.C19deaths.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(COVID.<span class="fl">19.</span>Deaths<span class="sc">~</span>Total.Deaths</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                   , ZC.data)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract intercept and coefficient(s)</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>ZC.TheseCoefs <span class="ot">&lt;-</span> ZC.C19deaths.lm<span class="sc">$</span>coefficients</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>ZC.C19deaths.intercept <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">1</span>]</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>ZC.C19deaths.AllDeaths <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">2</span>]</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Display model summary</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ZC.C19deaths.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = COVID.19.Deaths ~ Total.Deaths, data = ZC.data)

Residuals:
    Min      1Q  Median      3Q     Max 
-637.69  -14.66    3.94    7.41 2198.99 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -7.4149802  0.5999044  -12.36   &lt;2e-16 ***
Total.Deaths  0.1240340  0.0008414  147.41   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 82.78 on 27085 degrees of freedom
  (25383 observations deleted due to missingness)
Multiple R-squared:  0.4451,    Adjusted R-squared:  0.4451 
F-statistic: 2.173e+04 on 1 and 27085 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear Regression for PneuDeaths</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>ZC.PneuDeaths.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Pneumonia.Deaths<span class="sc">~</span>Total.Deaths</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                       , ZC.data)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract intercept and coefficient(s)</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>ZC.TheseCoefs <span class="ot">&lt;-</span> ZC.PneuDeaths.lm<span class="sc">$</span>coefficients</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>ZC.PneuDeaths.intercept <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">1</span>]</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>ZC.PneuDeaths.AllDeaths <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">2</span>]</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Display model summary</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ZC.PneuDeaths.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Pneumonia.Deaths ~ Total.Deaths, data = ZC.data)

Residuals:
    Min      1Q  Median      3Q     Max 
-277.23  -11.42    3.55    7.03 1419.10 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -7.0296503  0.3479068  -20.21   &lt;2e-16 ***
Total.Deaths  0.1160765  0.0004713  246.29   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 45.53 on 26088 degrees of freedom
  (26380 observations deleted due to missingness)
Multiple R-squared:  0.6993,    Adjusted R-squared:  0.6993 
F-statistic: 6.066e+04 on 1 and 26088 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear Regression for FluDeaths</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>ZC.FluDeaths.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Influenza.Deaths<span class="sc">~</span>Total.Deaths</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>                      , ZC.data)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract intercept and coefficient(s)</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>ZC.TheseCoefs <span class="ot">&lt;-</span> ZC.FluDeaths.lm<span class="sc">$</span>coefficients</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>ZC.FluDeaths.intercept <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">1</span>]</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>ZC.FluDeaths.AllDeaths  <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">2</span>]</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Display model summary</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ZC.FluDeaths.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Influenza.Deaths ~ Total.Deaths, data = ZC.data)

Residuals:
    Min      1Q  Median      3Q     Max 
-11.919  -0.238   0.103   0.207 111.833 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -2.514e-01  1.389e-02  -18.10   &lt;2e-16 ***
Total.Deaths  2.031e-03  2.976e-05   68.22   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.219 on 33843 degrees of freedom
  (18625 observations deleted due to missingness)
Multiple R-squared:  0.1209,    Adjusted R-squared:  0.1209 
F-statistic:  4654 on 1 and 33843 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear Regression for C19andPneuDeaths</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>ZC.C19andPneuDeaths.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Pneumonia.and.COVID.<span class="fl">19.</span>Deaths<span class="sc">~</span>(COVID.<span class="fl">19.</span>Deaths<span class="sc">+</span>Pneumonia.Deaths)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>                                                         , ZC.data)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract intercept and coefficient(s)</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>ZC.TheseCoefs <span class="ot">&lt;-</span> ZC.C19andPneuDeaths.lm<span class="sc">$</span>coefficients</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>ZC.C19andPneuDeaths.intercept <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">1</span>]</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>ZC.C19andPneuDeaths.C19deaths <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">2</span>]</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>ZC.C19andPneuDeaths.PneuDeaths <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">3</span>]</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Display model summary</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ZC.C19andPneuDeaths.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Pneumonia.and.COVID.19.Deaths ~ (COVID.19.Deaths + 
    Pneumonia.Deaths), data = ZC.data)

Residuals:
    Min      1Q  Median      3Q     Max 
-276.06    0.83    2.42    2.42  334.54 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      -2.417592   0.081587  -29.63   &lt;2e-16 ***
COVID.19.Deaths   0.389835   0.001893  205.95   &lt;2e-16 ***
Pneumonia.Deaths  0.204240   0.002536   80.55   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.3 on 27106 degrees of freedom
  (25361 observations deleted due to missingness)
Multiple R-squared:  0.9595,    Adjusted R-squared:  0.9595 
F-statistic: 3.21e+05 on 2 and 27106 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear Regression for C19orFluOrPneuDeaths</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>ZC.C19orFluOrPneuDeaths.lm <span class="ot">&lt;-</span> <span class="fu">lm</span> (Pneumonia..Influenza..or.COVID.<span class="fl">19.</span>Deaths<span class="sc">~</span>(COVID.<span class="fl">19.</span>Deaths<span class="sc">+</span>Pneumonia.Deaths<span class="sc">+</span>Influenza.Deaths)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>                                  , ZC.data)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract intercept and coefficient(s)</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>ZC.TheseCoefs <span class="ot">&lt;-</span> ZC.C19orFluOrPneuDeaths.lm<span class="sc">$</span>coefficients</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>ZC.C19orFluOrPneuDeaths.intercept <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">1</span>]</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>ZC.C19orFluOrPneuDeaths.C19deaths <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">2</span>]</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>ZC.C19orFluOrPneuDeaths.PneuDeaths <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">3</span>]</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>ZC.C19orFluOrPneuDeaths.FluDeaths  <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">4</span>]</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Display model summary</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ZC.C19orFluOrPneuDeaths.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Pneumonia..Influenza..or.COVID.19.Deaths ~ (COVID.19.Deaths + 
    Pneumonia.Deaths + Influenza.Deaths), data = ZC.data)

Residuals:
     Min       1Q   Median       3Q      Max 
-194.809   -1.378   -1.378   -0.654  270.532 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      1.378333   0.053070   25.97   &lt;2e-16 ***
COVID.19.Deaths  0.606038   0.001554  389.96   &lt;2e-16 ***
Pneumonia.Deaths 0.819092   0.002099  390.14   &lt;2e-16 ***
Influenza.Deaths 2.039785   0.019392  105.18   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.887 on 26340 degrees of freedom
  (26126 observations deleted due to missingness)
Multiple R-squared:  0.9923,    Adjusted R-squared:  0.9923 
F-statistic: 1.126e+06 on 3 and 26340 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear Regression for AllDeaths</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>ZC.AllDeaths.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Total.Deaths<span class="sc">~</span>(COVID.<span class="fl">19.</span>Deaths<span class="sc">+</span>Pneumonia.Deaths<span class="sc">+</span>Influenza.Deaths)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                      , ZC.data)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract intercept and coefficient(s)</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>ZC.TheseCoefs <span class="ot">&lt;-</span> ZC.AllDeaths.lm<span class="sc">$</span>coefficients</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>ZC.AllDeaths.intercept <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">1</span>]</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>ZC.AllDeaths.C19deaths <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">2</span>]</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>ZC.AllDeaths.PneuDeaths <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">3</span>]</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>ZC.AllDeaths.FluDeaths  <span class="ot">&lt;-</span> ZC.TheseCoefs[<span class="dv">4</span>]</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Display model summary</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ZC.AllDeaths.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Total.Deaths ~ (COVID.19.Deaths + Pneumonia.Deaths + 
    Influenza.Deaths), data = ZC.data)

Residuals:
    Min      1Q  Median      3Q     Max 
-3403.3   -86.2   -61.9    48.0  4349.1 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      86.23428    1.95620   44.08   &lt;2e-16 ***
COVID.19.Deaths  -4.22938    0.04366  -96.88   &lt;2e-16 ***
Pneumonia.Deaths 11.87907    0.06021  197.29   &lt;2e-16 ***
Influenza.Deaths 11.45774    0.54269   21.11   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 220.6 on 16971 degrees of freedom
  (35495 observations deleted due to missingness)
Multiple R-squared:  0.8259,    Adjusted R-squared:  0.8259 
F-statistic: 2.684e+04 on 3 and 16971 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>A linear regression model for each value to be synthesized has now been created.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tracking processing time</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>ZC.prep.time <span class="ot">&lt;-</span> <span class="fu">proc.time</span>() <span class="sc">-</span> ZC.prep.start</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ZC.ReportTime</span>(<span class="st">"Preparation"</span>, ZC.prep.time)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The Preparation section took 0.11 seconds of CPU time."
[1] "The Preparation section took 1.11 seconds of user time."
[1] "The Preparation section took 1.42 seconds of total time."</code></pre>
</div>
</div>
</section>
<section id="work-product-generation" class="level3">
<h3 class="anchored" data-anchor-id="work-product-generation">Work Product Generation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tracking processing time</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>ZC.gen.start <span class="ot">&lt;-</span> <span class="fu">proc.time</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Given that the model dataset and the synthesized dataset have the same number of rows, the synthesis is simplified: the original values for each combination of Year+Month+State+Gender+AgeGroup already exist. Columns for the six (6) values to be synthesized will be created, and the linear equation from the models developed earlier for each column will be applied.</p>
<p>A new, final synthesized dataset will be created from the identity columns (Year, Month, State, Gender, and AgeGroup) and the columns containing the newly-synthesized data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create objects used for multiple syntheses</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>ZC.RowRange <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(ZC.data)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Add synthesized columns to dataset, seeding with initial value of zero</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>ZC.data<span class="sc">$</span>C19deaths <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>ZC.data<span class="sc">$</span>PneuDeaths <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>ZC.data<span class="sc">$</span>FluDeaths <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>ZC.data<span class="sc">$</span>C19andPneuDeaths <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>ZC.data<span class="sc">$</span>C19orFluOrPneuDeaths <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>ZC.data<span class="sc">$</span>AllDeaths <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ZC.ReportDF</span>(<span class="st">"ready-for-synthesis"</span>, ZC.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The ready-for-synthesis dataframe is 52470 rows by 17 columns, and takes 5.41 Mb of space."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loop through the rows and populate the synthesized data</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (ZC.ThisRow <span class="cf">in</span> ZC.RowRange)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Synthesize C19deaths</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Gather variable(s) used by the linear regression model for synthesis</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># If they are NA, substitute a similar value</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.na</span>(ZC.data<span class="sc">$</span>Total.Deaths[ZC.ThisRow]))</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>  {</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># variable required for function is missing</span></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>    ZC.AllDeaths <span class="ot">&lt;-</span> <span class="fu">mean</span>(ZC.data<span class="sc">$</span>Total.Deaths,</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>                         <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>  {</span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># variable is present</span></span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>    ZC.AllDeaths <span class="ot">&lt;-</span> ZC.data<span class="sc">$</span>Total.Deaths[ZC.ThisRow]</span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Apply the function from the linear regression model</span></span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>  ZC.C19deaths <span class="ot">&lt;-</span> ZC.C19deaths.AllDeaths<span class="sc">*</span>ZC.AllDeaths <span class="sc">+</span> ZC.C19deaths.intercept</span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># need an integer value</span></span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a>  ZC.C19deaths <span class="ot">&lt;-</span> <span class="fu">round</span>(ZC.C19deaths, <span class="at">digits=</span><span class="dv">0</span>)</span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># can't have a negative number</span></span>
<span id="cb51-23"><a href="#cb51-23" aria-hidden="true" tabindex="-1"></a>  ZC.C19deaths <span class="ot">&lt;-</span> <span class="fu">abs</span>(ZC.C19deaths)</span>
<span id="cb51-24"><a href="#cb51-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># store the synthesized value</span></span>
<span id="cb51-25"><a href="#cb51-25" aria-hidden="true" tabindex="-1"></a>  ZC.data<span class="sc">$</span>C19deaths[ZC.ThisRow] <span class="ot">&lt;-</span> ZC.C19deaths</span>
<span id="cb51-26"><a href="#cb51-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-27"><a href="#cb51-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Synthesize PneuDeaths</span></span>
<span id="cb51-28"><a href="#cb51-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Gather variable(s) used by the linear regression model for synthesis</span></span>
<span id="cb51-29"><a href="#cb51-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># If they are NA, substitute a similar value</span></span>
<span id="cb51-30"><a href="#cb51-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># variable already gathered/assessed/assigned</span></span>
<span id="cb51-31"><a href="#cb51-31" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Apply the function from the linear regression model</span></span>
<span id="cb51-32"><a href="#cb51-32" aria-hidden="true" tabindex="-1"></a>  ZC.PneuDeaths <span class="ot">&lt;-</span> ZC.PneuDeaths.AllDeaths<span class="sc">*</span>ZC.AllDeaths <span class="sc">+</span> ZC.PneuDeaths.intercept</span>
<span id="cb51-33"><a href="#cb51-33" aria-hidden="true" tabindex="-1"></a>  <span class="co"># need an integer value</span></span>
<span id="cb51-34"><a href="#cb51-34" aria-hidden="true" tabindex="-1"></a>  ZC.PneuDeaths <span class="ot">&lt;-</span> <span class="fu">round</span>(ZC.PneuDeaths, <span class="at">digits=</span><span class="dv">0</span>)</span>
<span id="cb51-35"><a href="#cb51-35" aria-hidden="true" tabindex="-1"></a>  <span class="co"># can't have a negative number</span></span>
<span id="cb51-36"><a href="#cb51-36" aria-hidden="true" tabindex="-1"></a>  ZC.PneuDeaths <span class="ot">&lt;-</span> <span class="fu">abs</span>(ZC.PneuDeaths)</span>
<span id="cb51-37"><a href="#cb51-37" aria-hidden="true" tabindex="-1"></a>  <span class="co"># store the synthesized value</span></span>
<span id="cb51-38"><a href="#cb51-38" aria-hidden="true" tabindex="-1"></a>  ZC.data<span class="sc">$</span>PneuDeaths[ZC.ThisRow] <span class="ot">&lt;-</span> ZC.PneuDeaths</span>
<span id="cb51-39"><a href="#cb51-39" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-40"><a href="#cb51-40" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Synthesize FluDeaths</span></span>
<span id="cb51-41"><a href="#cb51-41" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Gather variable(s) used by the linear regression model for synthesis</span></span>
<span id="cb51-42"><a href="#cb51-42" aria-hidden="true" tabindex="-1"></a>  <span class="co"># If they are NA, substitute a similar value</span></span>
<span id="cb51-43"><a href="#cb51-43" aria-hidden="true" tabindex="-1"></a>  <span class="co"># variable already gathered/assessed/assigned</span></span>
<span id="cb51-44"><a href="#cb51-44" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Apply the function from the linear regression model</span></span>
<span id="cb51-45"><a href="#cb51-45" aria-hidden="true" tabindex="-1"></a>  ZC.FluDeaths <span class="ot">&lt;-</span> ZC.FluDeaths.AllDeaths<span class="sc">*</span>ZC.AllDeaths <span class="sc">+</span> ZC.FluDeaths.intercept</span>
<span id="cb51-46"><a href="#cb51-46" aria-hidden="true" tabindex="-1"></a>  <span class="co"># need an integer value</span></span>
<span id="cb51-47"><a href="#cb51-47" aria-hidden="true" tabindex="-1"></a>  ZC.FluDeaths <span class="ot">&lt;-</span> <span class="fu">round</span>(ZC.FluDeaths, <span class="at">digits=</span><span class="dv">0</span>)</span>
<span id="cb51-48"><a href="#cb51-48" aria-hidden="true" tabindex="-1"></a>  <span class="co"># can't have a negative number</span></span>
<span id="cb51-49"><a href="#cb51-49" aria-hidden="true" tabindex="-1"></a>  ZC.FluDeaths <span class="ot">&lt;-</span> <span class="fu">abs</span>(ZC.FluDeaths)</span>
<span id="cb51-50"><a href="#cb51-50" aria-hidden="true" tabindex="-1"></a>  <span class="co"># store the synthesized value</span></span>
<span id="cb51-51"><a href="#cb51-51" aria-hidden="true" tabindex="-1"></a>  ZC.data<span class="sc">$</span>FluDeaths[ZC.ThisRow] <span class="ot">&lt;-</span> ZC.FluDeaths</span>
<span id="cb51-52"><a href="#cb51-52" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-53"><a href="#cb51-53" aria-hidden="true" tabindex="-1"></a>  <span class="co"># All variables needed to finish regressions have been collected</span></span>
<span id="cb51-54"><a href="#cb51-54" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-55"><a href="#cb51-55" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Synthesize C19andPneuDeaths</span></span>
<span id="cb51-56"><a href="#cb51-56" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Apply the function from the linear regression model</span></span>
<span id="cb51-57"><a href="#cb51-57" aria-hidden="true" tabindex="-1"></a>  ZC.C19andPneuDeaths <span class="ot">&lt;-</span> ZC.C19andPneuDeaths.C19deaths<span class="sc">*</span>ZC.C19deaths <span class="sc">+</span> ZC.C19andPneuDeaths.PneuDeaths<span class="sc">*</span>ZC.PneuDeaths <span class="sc">+</span> ZC.C19andPneuDeaths.intercept</span>
<span id="cb51-58"><a href="#cb51-58" aria-hidden="true" tabindex="-1"></a>  <span class="co"># need an integer value</span></span>
<span id="cb51-59"><a href="#cb51-59" aria-hidden="true" tabindex="-1"></a>  ZC.C19andPneuDeaths <span class="ot">&lt;-</span> <span class="fu">round</span>(ZC.C19andPneuDeaths, <span class="at">digits=</span><span class="dv">0</span>)</span>
<span id="cb51-60"><a href="#cb51-60" aria-hidden="true" tabindex="-1"></a>  <span class="co"># can't have a negative number</span></span>
<span id="cb51-61"><a href="#cb51-61" aria-hidden="true" tabindex="-1"></a>  ZC.C19andPneuDeaths <span class="ot">&lt;-</span> <span class="fu">abs</span>(ZC.C19andPneuDeaths)</span>
<span id="cb51-62"><a href="#cb51-62" aria-hidden="true" tabindex="-1"></a>  <span class="co"># store the synthesized value</span></span>
<span id="cb51-63"><a href="#cb51-63" aria-hidden="true" tabindex="-1"></a>  ZC.data<span class="sc">$</span>C19andPneuDeaths[ZC.ThisRow] <span class="ot">&lt;-</span> ZC.C19andPneuDeaths</span>
<span id="cb51-64"><a href="#cb51-64" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-65"><a href="#cb51-65" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Synthesize C19orFluOrPneuDeaths</span></span>
<span id="cb51-66"><a href="#cb51-66" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Apply the function from the linear regression model</span></span>
<span id="cb51-67"><a href="#cb51-67" aria-hidden="true" tabindex="-1"></a>  ZC.C19orFluOrPneuDeaths <span class="ot">&lt;-</span> ZC.C19orFluOrPneuDeaths.C19deaths<span class="sc">*</span>ZC.C19deaths <span class="sc">+</span> ZC.C19orFluOrPneuDeaths.PneuDeaths<span class="sc">*</span>ZC.PneuDeaths <span class="sc">+</span> ZC.C19orFluOrPneuDeaths.FluDeaths<span class="sc">*</span>ZC.FluDeaths <span class="sc">+</span> ZC.C19orFluOrPneuDeaths.intercept</span>
<span id="cb51-68"><a href="#cb51-68" aria-hidden="true" tabindex="-1"></a>  <span class="co"># need an integer value</span></span>
<span id="cb51-69"><a href="#cb51-69" aria-hidden="true" tabindex="-1"></a>  ZC.C19orFluOrPneuDeaths <span class="ot">&lt;-</span> <span class="fu">round</span>(ZC.C19orFluOrPneuDeaths, <span class="at">digits=</span><span class="dv">0</span>)</span>
<span id="cb51-70"><a href="#cb51-70" aria-hidden="true" tabindex="-1"></a>  <span class="co"># can't have a negative number</span></span>
<span id="cb51-71"><a href="#cb51-71" aria-hidden="true" tabindex="-1"></a>  ZC.C19orFluOrPneuDeaths <span class="ot">&lt;-</span> <span class="fu">abs</span>(ZC.C19orFluOrPneuDeaths)</span>
<span id="cb51-72"><a href="#cb51-72" aria-hidden="true" tabindex="-1"></a>  <span class="co"># store the synthesized value</span></span>
<span id="cb51-73"><a href="#cb51-73" aria-hidden="true" tabindex="-1"></a>  ZC.data<span class="sc">$</span>C19orFluOrPneuDeaths[ZC.ThisRow] <span class="ot">&lt;-</span> ZC.C19orFluOrPneuDeaths</span>
<span id="cb51-74"><a href="#cb51-74" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-75"><a href="#cb51-75" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Synthesize AllDeaths</span></span>
<span id="cb51-76"><a href="#cb51-76" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Reusing ZC.AllDeaths because its previous use is now deprecated</span></span>
<span id="cb51-77"><a href="#cb51-77" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Apply the function from the linear regression model</span></span>
<span id="cb51-78"><a href="#cb51-78" aria-hidden="true" tabindex="-1"></a>  ZC.AllDeaths <span class="ot">&lt;-</span> ZC.AllDeaths.C19deaths<span class="sc">*</span>ZC.C19deaths <span class="sc">+</span> ZC.AllDeaths.PneuDeaths<span class="sc">*</span>ZC.PneuDeaths <span class="sc">+</span> ZC.AllDeaths.FluDeaths<span class="sc">*</span>ZC.FluDeaths <span class="sc">+</span> ZC.AllDeaths.intercept</span>
<span id="cb51-79"><a href="#cb51-79" aria-hidden="true" tabindex="-1"></a>  <span class="co"># need an integer value</span></span>
<span id="cb51-80"><a href="#cb51-80" aria-hidden="true" tabindex="-1"></a>  ZC.AllDeaths <span class="ot">&lt;-</span> <span class="fu">round</span>(ZC.AllDeaths, <span class="at">digits=</span><span class="dv">0</span>)</span>
<span id="cb51-81"><a href="#cb51-81" aria-hidden="true" tabindex="-1"></a>  <span class="co"># can't have a negative number</span></span>
<span id="cb51-82"><a href="#cb51-82" aria-hidden="true" tabindex="-1"></a>  ZC.AllDeaths <span class="ot">&lt;-</span> <span class="fu">abs</span>(ZC.AllDeaths)</span>
<span id="cb51-83"><a href="#cb51-83" aria-hidden="true" tabindex="-1"></a>  <span class="co"># store the synthesized value</span></span>
<span id="cb51-84"><a href="#cb51-84" aria-hidden="true" tabindex="-1"></a>  ZC.data<span class="sc">$</span>AllDeaths[ZC.ThisRow] <span class="ot">&lt;-</span> ZC.AllDeaths</span>
<span id="cb51-85"><a href="#cb51-85" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb51-86"><a href="#cb51-86" aria-hidden="true" tabindex="-1"></a><span class="fu">ZC.ReportDF</span>(<span class="st">"synthesized"</span>, ZC.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The synthesized dataframe is 52470 rows by 17 columns, and takes 5.41 Mb of space."</code></pre>
</div>
</div>
<p>Here are the basic statistics regarding the synthesized data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ZC.data<span class="sc">$</span>C19deaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    0.0     5.0    18.0    32.7    30.0  1016.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ZC.data<span class="sc">$</span>PneuDeaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    5.00   17.00   30.59   28.00  950.00 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ZC.data<span class="sc">$</span>FluDeaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  0.0000  0.3365  0.0000 16.0000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ZC.data<span class="sc">$</span>C19andPneuDeaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    1.00    8.00   17.06   15.00  588.00 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ZC.data<span class="sc">$</span>C19orFluOrPneuDeaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1.00    9.00   26.00   46.84   42.00 1428.00 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ZC.data<span class="sc">$</span>AllDeaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   82.0   120.0   212.0   315.2   292.0  7258.0 </code></pre>
</div>
</div>
<p>Now the final synthesized dataset will be constructed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>ZC.synthed <span class="ot">&lt;-</span> ZC.data[<span class="fu">c</span>(<span class="st">"Year"</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"Month"</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"State"</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"Sex"</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"Age.Group"</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"C19deaths"</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"PneuDeaths"</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"FluDeaths"</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"C19andPneuDeaths"</span></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"C19orFluOrPneuDeaths"</span></span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>                      , <span class="st">"AllDeaths"</span></span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>                      )</span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Finalize a couple of column name changes</span></span>
<span id="cb65-15"><a href="#cb65-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ZC.ReportDF</span>(<span class="st">"finalized"</span>, ZC.synthed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The finalized dataframe is 52470 rows by 11 columns, and takes 4.21 Mb of space."</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tracking processing time</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>ZC.gen.time <span class="ot">&lt;-</span> <span class="fu">proc.time</span>() <span class="sc">-</span> ZC.gen.start</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ZC.ReportTime</span>(<span class="st">"Generation"</span>, ZC.gen.time)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The Generation section took 28.58 seconds of CPU time."
[1] "The Generation section took 44.35 seconds of user time."
[1] "The Generation section took 74.77 seconds of total time."</code></pre>
</div>
</div>
</section>
<section id="end-of-part-2" class="level3">
<h3 class="anchored" data-anchor-id="end-of-part-2">End of Part 2</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tracking processing time</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>ZC.Part2.time <span class="ot">&lt;-</span> <span class="fu">proc.time</span>() <span class="sc">-</span> ZC.Part2.start</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ZC.ReportTime</span>(<span class="st">"Part 2"</span>, ZC.Part2.time)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The Part 2 section took 28.75 seconds of CPU time."
[1] "The Part 2 section took 45.5 seconds of user time."
[1] "The Part 2 section took 76.31 seconds of total time."</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>